# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 22:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edure', '0002_drivestorage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timestamp_mod', models.DateTimeField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('files', models.FileField(upload_to=b'upload')),
                ('types', models.CharField(blank=True, choices=[(b'filesystem', b'File System'), (b'dropbox', b'Dropbox'), (b'gdrive', b'Google Drive')], max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='drivestorage',
            name='user',
        ),
        migrations.DeleteModel(
            name='DriveStorage',
        ),
    ]
