# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edure', '0003_auto_20171218_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='alternate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='bytes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='storage',
            name='icon',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='isDir',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edure.Storage'),
        ),
    ]
