# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-24 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edure', '0004_auto_20171220_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
