# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edure', '0006_storage_ext'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('venue', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('price', models.CharField(blank=True, max_length=250, null=True)),
                ('events_overview', models.CharField(max_length=550)),
                ('tags', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='interested',
            field=models.ManyToManyField(blank=True, to='edure.SubTopic'),
        ),
    ]
