# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-08 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edure', '0007_auto_20180108_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='events_overview',
            field=models.CharField(max_length=50000),
        ),
    ]
